controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_outer_knuckle_joint
initial:  # Define initial robot poses.
  - group: gripper
    pose: open